//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETARaporlama.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADRESLER
    {
        public int ADRMODUL { get; set; }
        public int ADRKONU { get; set; }
        public int ADRTIP { get; set; }
        public string ADRKOD1 { get; set; }
        public string ADRKOD2 { get; set; }
        public int ADRREFNO { get; set; }
        public int ADRITEMNO { get; set; }
        public string ADRYETKILI { get; set; }
        public string ADRADRES1 { get; set; }
        public string ADRADRES2 { get; set; }
        public string ADRADRES3 { get; set; }
        public string ADRPOSTAKOD { get; set; }
        public string ADRULKE { get; set; }
        public string ADRIL { get; set; }
        public string ADRILCE { get; set; }
        public string ADRTEL1 { get; set; }
        public string ADRTEL2 { get; set; }
        public string ADRTEL3 { get; set; }
        public string ADRFAX1 { get; set; }
        public string ADRFAX2 { get; set; }
        public string ADRFAX3 { get; set; }
        public string ADREMAIL1 { get; set; }
        public string ADREMAIL2 { get; set; }
        public string ADREMAIL3 { get; set; }
        public string ADRURL1 { get; set; }
        public string ADRURL2 { get; set; }
        public string ADRURL3 { get; set; }
    }
}
