//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETARaporlama.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARKART
    {
        public string CARKOD { get; set; }
        public string CARUNVAN { get; set; }
        public string CARUNVAN2 { get; set; }
        public string CARUNVAN3 { get; set; }
        public string CARYETKILI { get; set; }
        public string CARYETKILI2 { get; set; }
        public string CARYETKILI3 { get; set; }
        public string CAROZKOD1 { get; set; }
        public string CAROZKOD2 { get; set; }
        public string CAROZKOD3 { get; set; }
        public string CAROZKOD4 { get; set; }
        public string CAROZKOD5 { get; set; }
        public string CARDOVKOD1 { get; set; }
        public string CARDOVTUR1 { get; set; }
        public string CARDOVKOD2 { get; set; }
        public string CARDOVTUR2 { get; set; }
        public string CARDOVKOD3 { get; set; }
        public string CARDOVTUR3 { get; set; }
        public string CARDOVKOD4 { get; set; }
        public string CARDOVTUR4 { get; set; }
        public string CARDOVKOD5 { get; set; }
        public string CARDOVTUR5 { get; set; }
        public string CARVERDAIRE { get; set; }
        public string CARVERHESNO { get; set; }
        public string CAROZELKARTNO { get; set; }
        public string CARODASICILNO { get; set; }
        public string CARACIK1 { get; set; }
        public string CARACIK2 { get; set; }
        public string CARACIK3 { get; set; }
        public string CARACIK4 { get; set; }
        public string CARACIK5 { get; set; }
        public int CARCALFLAG { get; set; }
        public string CARDERECE { get; set; }
        public string CARUYARI { get; set; }
        public decimal CARISKYUZ { get; set; }
        public int CARMUAFGUN { get; set; }
        public string CARTAHSILKOD { get; set; }
        public string CARTAHSILACK { get; set; }
        public decimal CARKREDILIMIT { get; set; }
        public decimal CARRISKLIMIT { get; set; }
        public decimal CARSIPALIMLIMIT { get; set; }
        public decimal CARSIPSATIMLIMIT { get; set; }
        public int CARHESAPGUN { get; set; }
        public string CARVADENO { get; set; }
        public string CARODEPLANGRUPNO { get; set; }
        public string CARTAKSITGRUPNO { get; set; }
        public System.DateTime CARMUTABAKATTAR { get; set; }
        public decimal CARMUTABAKATTUT { get; set; }
        public string CARGRUPKODU { get; set; }
        public string CARSEKTORKODU { get; set; }
        public string CARBOLGEKODU { get; set; }
        public string CARSTKALISFIYNO { get; set; }
        public string CARSTKSATISFIYNO { get; set; }
        public string CARLISFIYNO { get; set; }
        public string CARKEFILKODU1 { get; set; }
        public string CARKEFILKODU2 { get; set; }
        public string CARKEFILKODU3 { get; set; }
        public string CARKEFILKODU4 { get; set; }
        public string CARKEFILKODU5 { get; set; }
        public int CARMUHTIPI { get; set; }
        public string CARMUHKODU { get; set; }
        public int CARYAZADRNO { get; set; }
        public int CARFATADRNO { get; set; }
        public int CARIRSADRNO { get; set; }
        public decimal CARBORCTOP { get; set; }
        public decimal CARALACAKTOP { get; set; }
        public decimal CARBAKIYE { get; set; }
        public string CARKREDIDOVKOD { get; set; }
        public string CARKREDIDOVTUR { get; set; }
        public string CARRISKDOVKOD { get; set; }
        public string CARRISKDOVTUR { get; set; }
        public decimal CARTEMINATTUT { get; set; }
        public string CARTEMDOVKOD { get; set; }
        public string CARTEMDOVTUR { get; set; }
        public string CARGRUPKOD { get; set; }
        public int CARKARALISTEFLAG { get; set; }
        public string CARKARALISTEACK { get; set; }
        public int CARSEVNO { get; set; }
        public decimal CARGIRIRSTOP { get; set; }
        public decimal CARCIKIRSTOP { get; set; }
        public decimal CARGIRSIPTOPTUT { get; set; }
        public decimal CARCIKSIPTOPTUT { get; set; }
        public int CARGIRSIPTUTFLAG { get; set; }
        public decimal CARGIRSIPMINTUT { get; set; }
        public decimal CARGIRSIPMAXTUT { get; set; }
        public int CARCIKSIPTUTFLAG { get; set; }
        public decimal CARCIKSIPMINTUT { get; set; }
        public decimal CARCIKSIPMAXTUT { get; set; }
        public decimal CAROZELBORCTOP { get; set; }
        public decimal CAROZELALACAKTOP { get; set; }
        public decimal CAROZELBAKIYE { get; set; }
        public string CAREKCHAR1 { get; set; }
        public string CAREKCHAR2 { get; set; }
        public int CAREKINT1 { get; set; }
        public int CAREKINT2 { get; set; }
        public System.DateTime CAREKDATE1 { get; set; }
        public System.DateTime CAREKDATE2 { get; set; }
        public decimal CAREKDBL1 { get; set; }
        public decimal CAREKDBL2 { get; set; }
        public int CAREFATFLAG { get; set; }
        public int CAREFATSENARYO { get; set; }
        public string CAREFATEMAIL { get; set; }
        public int CAREFATDONEMTIP { get; set; }
        public int CAREFATDONEMDEG { get; set; }
    }
}
